### ISSUE TITLE
Support other alerting methods

### ISSUE THREAD

**Issue by wpjunior** [globocom/slo-generator#3]
Other methods are described in SRE workbook chapter: alerting on SLO

**Comment by rodrigo-brito** [comment]
Hi @wpjunior, I will try to include Burn Rate Alert.
I saw an interface  `AlertMethod` to be implemented in `method` folder, it's the right place? How can I test it?

**Comment by wpjunior** [comment]
Hi @rodrigo-brito yeah, there is a right place, the tests nowadays just uses the generated promql string to assert the result, this alert-method is the last one to full implement all alert methods of SRE.
